### ISSUE TITLE
Bug: Every time you update the home bridge plugin you break things!!

### ISSUE THREAD

**Issue by CryptoKnight360** [OpenWonderLabs/homebridge-switchbot#1150]
### Describe the Bug

You guys are the MOST incompetent developers, if u even deserve to be called that. STOP fucking updating your plugin and breaking stuff. I paid for these shitty fucking devices and half the time they don't fucking work!!!

### To Reproduce

You guys are the MOST incompetent developers, if u even deserve to be called that. STOP fucking updating your plugin and breaking stuff. I paid for these shitty fucking devices and half the time they don't fucking work!!!

### Expected Behavior

You guys are the MOST incompetent developers, if u even deserve to be called that. STOP fucking updating your plugin and breaking stuff. I paid for these shitty fucking devices and half the time they don't fucking work!!!

### Relevant Log Output

```shell

```

### Config for homebridge-switchbot

```shell

```

### Node.js Version

12.21.21

### NPM Version

7.22.2

### Homebridge Version

1.3.4

### Homebridge Switchbot Plugin Version

4.1.6

### Operating System

MacOS

**Comment by donavanbecker** [comment]
Well not seeing any logs provided so not much we can do to help you.

**Comment by CryptoKnight360** [comment]
Homebridge logs say that the plugin can't connect to several AWS servers. The usual BS with Switchbot. Homebridge logs also show that this plugin and the Switchbot ecosystem are the most GARBAGE ecosystem any person can install in their homes. That's what the logs say.

**Comment by donavanbecker** [comment]
Those kind of logs were never coded into the plugin, so you must be using the wrong plugin.

**Comment by CryptoKnight360** [comment]
Been using the same Homebridge Plugin for almost a year now. It's attempting to connect to several AWS servers in Virginia and timing out. 




  
  
    
        
            
                
                    Crypto Knight Crypto & NFT Enthusiast(800) 555-0199(800) ***@***.*** King Am I Creek, Somewhere, NY 07001            
                    
	
        
            
                
                    
                    
                    
                    
                    
                
                
                    
                    
                    
                    
                    
                
               
                
                    
                    
    
  
  
On Dec 22, 2024, at 7:59 AM, Donavan Becker ***@***.***> wrote:﻿
Those kind of logs were never coded into the plugin, so you must be using the wrong plugin.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by CryptoKnight360** [comment]
> Those kind of logs were never coded into the plugin, so you must be using the wrong plugin.

[SwitchBot] Failed to get device status: Connect Timeout Error (attempted addresses: 54.198.113.220:443, 50.19.146.81:443, 3.234.78.251:443, timeout: 10000ms)
[12/21/2024, 9:50:34 PM] [SwitchBot] Error making request: Failed to get device status: Connect Timeout Error (attempted addresses: 54.198.113.220:443, 50.19.146.81:443, 3.234.78.251:443, timeout: 10000ms)
[12/21/2024, 9:50:47 PM] [SwitchBot] Failed to get device status: Connect Timeout Error (attempted addresses: 54.198.113.220:443, 50.19.146.81:443, 3.234.78.251:443, timeout: 10000ms)
[12/21/2024, 9:50:47 PM] [SwitchBot] Error making request: Failed to get device status: Connect Timeout Error (attempted addresses: 54.198.113.220:443, 50.19.146.81:443, 3.234.78.251:443, timeout: 10000ms)

Did Homebridge pull those IPs out of the clear blue sky?

**Comment by CryptoKnight360** [comment]
Also generates this error: "[SwitchBot] Bot: Buzzer Unknown statusCode: undefined, Submit Bugs Here: https://tinyurl.com/SwitchBotBug, statusCode: undefined" 



Plugin at least worked half the time before, now it refuses to work on Homekit at all. Been using this same plugin for a year unfortunately, and the logs point here via a URL to report bugs. So yes, this is YOUR plugin. Wish I could flash the bot with custom firmware for direct integration into HomeKit, but unfortunately that's not possible. The switchbot app and plugin have been the buggiest out the bunch in my smartphone.

**Comment by donavanbecker** [comment]
> Also generates this error: "[SwitchBot] Bot: Buzzer Unknown statusCode: undefined, Submit Bugs Here: https://tinyurl.com/SwitchBotBug, statusCode: undefined"
> 
> Plugin at least worked half the time before, now it refuses to work on Homekit at all. Been using this same plugin for a year unfortunately, and the logs point here via a URL to report bugs. So yes, this is YOUR plugin. Wish I could flash the bot with custom firmware for direct integration into HomeKit, but unfortunately that's not possible. The switchbot app and plugin have been the buggiest out the bunch in my smartphone.

this is resolved in the next release.

**Comment by CryptoKnight360** [comment]
I checked the Beta 4 and the same issue persists. So I have to wait till the next release for this to be resolved? Is this a normal thing? A device's TOTAL functionality breaks with an update and people have to wait till the next release for a fix?!? Some people use these devices for pretty important stuff like opening doors, electronic gates, etc etc, not just to turn on their coffee pots. And it seems like things break with every single update!! Like. Every. Single. One. And out of 100+ devices on HomeKit, of which many depend on Homebridge, Switchbot's devices, their matter implementation and Homebridge plugin are by far the ONLY problematic ones. They should allows us to flash these Bots with our own firmware if they can't get their act together. It's the least they can do since their own implementations and Homebridge Plugins they tout about are broken 50% of the damn time. There's literally PLACE HOLDERS for Temps and Ghost settings that are on the GUI for show purposes cause they don't work at all!!! What a waste of time and money. This is a total joke.

**Comment by donavanbecker** [comment]
I hope you have a Merry Christmas.
