### ISSUE TITLE
Bug: curtains not updating

### ISSUE THREAD

**Issue by sonezu** [OpenWonderLabs/homebridge-switchbot#123]
### Describe The Bug

updated from 0.1.1 to 1.2.5 on raspberry pi: curtain state seems to be constantly updating on the apple home app. Curtain states seem to be VERY unreliable on homebridge. 9 out of 10 the commands to open or close won't be received. Going back to v0.1.1 solved the problem.

### To Reproduce

Update from 0.1.1 to 1.2.5 and back

### Expected behavior

Showing the current state of the curtains and execute commands to open or close curtains

### Relevant log output

```shell
[27.11.2021, 12:09:40] [HB Supervisor] Starting Homebridge with extra flags: -I
[27.11.2021, 12:09:40] [HB Supervisor] Started Homebridge v1.3.8 with PID: 17263
[27.11.2021, 12:09:41] Loaded config.json with 0 accessories and 4 platforms.
[27.11.2021, 12:09:42] Loaded 2 cached accessories from cachedAccessories.
[27.11.2021, 12:09:42] ---
[27.11.2021, 12:09:43] Loaded plugin: homebridge-config-ui-x@4.41.3
[27.11.2021, 12:09:43] Registering platform 'homebridge-config-ui-x.config'
[27.11.2021, 12:09:43] ---
[27.11.2021, 12:09:43] Loaded plugin: homebridge-homematic@0.2.226
[27.11.2021, 12:09:43] Registering platform 'homebridge-homematic.HomeMatic'
[27.11.2021, 12:09:43] ---
[27.11.2021, 12:09:44] Loaded plugin: homebridge-samsung-tizen@5.1.0
[27.11.2021, 12:09:44] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[27.11.2021, 12:09:44] ---
[27.11.2021, 12:09:44] Loaded plugin: @switchbot/homebridge-switchbot@0.1.1
[27.11.2021, 12:09:44] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[27.11.2021, 12:09:44] ---
[27.11.2021, 12:09:44] Loading 4 platforms...
[27.11.2021, 12:09:44] [Config] Initializing config platform...
[27.11.2021, 12:09:44] [Config] Running in Service Mode
[27.11.2021, 12:09:44] [HomeMatic CCU] Initializing HomeMatic platform...
[27.11.2021, 12:09:44] [HomeMatic CCU] [Core] merging configurations
[27.11.2021, 12:09:44] [HomeMatic CCU] Homematic Plugin Version 0.2.226
[27.11.2021, 12:09:44] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[27.11.2021, 12:09:44] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[27.11.2021, 12:09:44] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[27.11.2021, 12:09:44] [HomeMatic CCU] running in production mode
[27.11.2021, 12:09:44] [HomeMatic CCU] will connect to your ccu at 192.168.178.20
[27.11.2021, 12:09:44] [HomeMatic CCU] IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/lib/homebridge/homematic_config.json
[27.11.2021, 12:09:44] [HomeMatic CCU] using subsection Homekit
[27.11.2021, 12:09:44] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-RF
[27.11.2021, 12:09:44] [HomeMatic CCU] init RPC for BidCos-RF.
[27.11.2021, 12:09:44] [HomeMatic CCU] [RPC] local ip used : 192.168.178.66. you may change that with local_ip parameter in config
[27.11.2021, 12:09:44] [HomeMatic CCU] init RPC for VirtualDevices.
[27.11.2021, 12:09:44] [HomeMatic CCU] [RPC] local ip used : 192.168.178.66. you may change that with local_ip parameter in config
[27.11.2021, 12:09:44] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-Wired
[27.11.2021, 12:09:44] [HomeMatic CCU] init RPC for BidCos-Wired.
[27.11.2021, 12:09:44] [HomeMatic CCU] [RPC] local ip used : 192.168.178.66. you may change that with local_ip parameter in config
[27.11.2021, 12:09:44] [HomeMatic CCU] init RPC for HmIP-RF.
[27.11.2021, 12:09:44] [HomeMatic CCU] [RPC] local ip used : 192.168.178.66. you may change that with local_ip parameter in config
[27.11.2021, 12:09:44] [SamsungTizen] Initializing SamsungTizen platform...
[27.11.2021, 12:09:44] [public@florian-kleinschmidt.de] Initializing SwitchBot platform...
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Using Default Push Rate.
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Loading accessory from cache: Vorhang links Curtain
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Loading accessory from cache: Vorhang rechts Curtain
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] server for interface BidCos-RF. is listening on port 9090.
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] server for interface VirtualDevices. is listening on port 9093.
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] server for interface BidCos-Wired. is listening on port 9091.
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] server for interface HmIP-RF. is listening on port 9092.
[27.11.2021, 12:09:45] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[27.11.2021, 12:09:45] Fernseher 71E9 is running on port 34865.
[27.11.2021, 12:09:45] Please add [Fernseher 71E9] manually in Home app. Setup Code: ((CENSORED))
[27.11.2021, 12:09:45] [HomeMatic CCU] if PONG is PONG CCU is alive
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Total SwitchBot Devices Found: 3
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Total IR Devices Found: 0
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Restoring existing accessory from cache: Vorhang links Curtain DeviceID: C2E5AE13CDBA
[27.11.2021, 12:09:45] [public@florian-kleinschmidt.de] Restoring existing accessory from cache: Vorhang rechts Curtain DeviceID: F0489DFAB664
[27.11.2021, 12:10:00] [HomeMatic CCU] [ServiceClassLoader] There is no service for VIR-LG-ONOFF:VIR-LG-ONOFF-CH
[27.11.2021, 12:10:00] [HomeMatic CCU] [ServiceClassLoader] There is no service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT
[27.11.2021, 12:10:00] Initializing platform accessory 'Haustür'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Arbeitszimmer'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Bad'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Esszimmer'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Gästebad'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Kinderzimmer'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Küche'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Wohnzimmer'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Wohnzimmer links'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Wohnzimmer rechts'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Heizung Flur'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Kühlschrank'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Thermostat Wohnzimmer Klima'...
[27.11.2021, 12:10:00] Initializing platform accessory 'Thermostat Wohnzimmer Heizung'...
Setup Payload:
X-HM://((CENSORED))
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ((CENSORED)) │     
    └────────────┘     
                       
[27.11.2021, 12:10:00] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge D145) is running on port 51805.
[27.11.2021, 12:10:00] [HomeMatic CCU] [Core] will cache ccu response to /var/lib/homebridge/ccu.json
[27.11.2021, 12:10:01] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[27.11.2021, 12:10:04] [HomeMatic CCU] [Core] NPM 0.2.226 vs Local 0.2.226
[27.11.2021, 12:12:02] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[27.11.2021, 12:12:54] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
```

### Config for homebridge-switchbot

```shell
{
    "name": "((CENSORED))",
    "credentials": {
        "openToken": "((CENSORED))",
        "notice": "Keep your token a secret!"
    },
    "options": {
        "refreshRate": 300
    },
    "devicediscovery": false,
    "platform": "SwitchBot"
}
```

### Device & Model

SwitchBot HubMini + CurtainBots

### Node.js Version

v16.13.0

### NPM Version

v6.14.15

### Homebridge Version

v1.3.8

### Homebridge Switchbot Plugin Version

v0.1.1

### Homebridge Config UI X Plugin Version

v4.41.3

### Operating System

Raspbian

**Comment by dieugab** [comment]
Similar stuff to #85. v0.1.1 works perfectly, and everything from 1.0 forward seems unreliable.

**Comment by donavanbecker** [comment]
@gvssr and @sonezu, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.7.1-beta.5/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by dnicolson** [comment]
Setting an arbitrary value for the "Set Min Lux" option results in the closed/open status working in the `set_min`/`set_max` range. More investigation is needed.

There appear to be caching issues that may be contributing to the issue though. For example, changing the `Device Name` option does not change the name until the cache is cleared.

**Comment by donavanbecker** [comment]
@dnicolson new beta has been published wit your PR #227. 

@gvssr @sonezu, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.10.2-beta.3/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
v1.11.0 has been release with this fix.

**Comment by dieugab** [comment]
@donavanbecker sorry te report this is still as broken as it’s been for me. Stays hanging on “closing” and “opening” and does not report the correct open / close state, even with min/max set.
![DA9AE797-42D9-4113-93FC-11EBF31AC834](https://user-images.githubusercontent.com/61377476/151675566-39fa08ca-957d-45df-be6b-8fe975f8100f.jpeg)
![89B0FDCB-28D6-4BE3-87A2-6D745D35E69E](https://user-images.githubusercontent.com/61377476/151675568-b9456560-b4ca-4f78-8a62-03330e609c52.jpeg)

For me, it’s a regression of 0.1.1 and unusable for my use case (in Home Assistant)

**Comment by dieugab** [comment]
@donavanbecker I mentioned this in the other thread, but maybe @dnicolson has some insight. An example:

I start with an open curtain like this:
![2ED91163-CBCB-4A93-A7AD-1092EF079A4E](https://user-images.githubusercontent.com/61377476/151676213-3d930f4a-8432-4ecb-be21-419005332ac4.jpeg)

I then send the command to close, it’ll say “closing” and hang on closing no matter how much time passes. It’s stuck on closing.
![00D2E93C-1966-4234-9BEF-495CE1114DCF](https://user-images.githubusercontent.com/61377476/151676232-af61435c-0f4c-4938-a334-02b8682f136a.jpeg)

However, when I reboot Homebridge…
![7AC9CCB6-B5B1-4ACD-897B-5C9A4ED8C279](https://user-images.githubusercontent.com/61377476/151676237-7a59bc8e-4212-4cb8-8c8c-c922240d2298.jpeg)

… it shows the correct state:
![7E2B3F3F-1AC7-437C-89B7-BECF29A4217F](https://user-images.githubusercontent.com/61377476/151676241-de9e5409-2a4f-4949-8a1f-f4b3b3ed16f9.jpeg)

Same thing other way around. It’ll be open, I close the curtain and it says “closing” until I reboot homebridge. **Correct state is only displayed after a reboot of homebridge**.

**Comment by donavanbecker** [comment]
@gvssr Have you set an updateRate? Also are you doing BLE?

**Comment by dieugab** [comment]
@donavanbecker no updateRate set (default is 5?) and it’s connected with BLE, but the same thing happens when using the API.

**Comment by donavanbecker** [comment]
@gvssr i am sorry, I really don't care if the Homebridge UI works or not, I am worried about the home app. So till I see a screenshot of the home app not working, I am marking this as resolved.

**Comment by donavanbecker** [comment]
Sorry not trying to blow this off but the Homebridge UI is not a priority for me and could be an issue with the Homebridge UI.

**Comment by dieugab** [comment]
@donavanbecker yeah that was the conclusion from the other thread, which is why I stopped using this plugin 🙂 but I got a @ notification from you asking to try the latest beta to see if it’s fixed so I figured I’d try it.

I don’t think it’s an issue with Homebridge UI exclusively, fwiw. It’s also reported like this in Home Assistant. I think the home app calculates closed and open state based on position and state, and ignores whether a cover is still “opening” or “closing”, where Homebridge and Home Assistant prioritize that value first. 0.1.1 of this plugin followed that same logic. I don’t use Switchbot in the Home app, where it probably works fine.

**Comment by dnicolson** [comment]
I don't believe it's a Homebridge UI issue. In the Home app the "Opening..." and "Closing..." states never appear, it always changes immediately to "Open" or "Closed". In Homebridge UI the "Opening..." and "Closing..." states never change to 
"Open" or "Closed".

The [homebridge-switchbot-ble](https://www.npmjs.com/package/@switchbot/homebridge-switchbot-ble) works in both the Home app and Homebridge UI. Is it possible to restore the GitHub repository for this? It makes it easier to see the old code to fix these issues.

**Comment by donavanbecker** [comment]
@dnicolson It is public now.

I am not having any of these issues, so until I get PRs, I don't have anything to test.

**Comment by dieugab** [comment]
> I don't believe it's a Homebridge UI issue. In the Home app the "Opening..." and "Closing..." states never appear, it always changes immediately to "Open" or "Closed". In Homebridge UI the "Opening..." and "Closing..." states never change to "Open" or "Closed".

This is exactly what I’m experiencing!

No idea if this helps @dnicolson (I don’t have any programming experience), but 0.1.1 version of this plugin did work using this code (I think): https://github.com/OpenWonderLabs/homebridge-switchbot/issues/85#issuecomment-979228867 But I don’t know what changed when BLE got integrated.

**Comment by dnicolson** [comment]
I can confirm that version 0.1.1 does not have the issue (although BLE was not working).

The problem appears to have been introduced in version 0.1.2-beta.1, it's related to the light sensor. Removing the following lines in the latest code appears to resolve the issue:
https://github.com/OpenWonderLabs/homebridge-switchbot/blob/dedabb43754f837c43d1d7ff3fbfc40e00d46877/src/device/curtain.ts#L121-L135

@donavanbecker can you also make [homebridge-switchbot-openapi](https://www.npmjs.com/package/homebridge-switchbot-openapi) available again? There is a broken image in the Homebridge SwitchBot BLE settings that is hosted on GitHub.

**Comment by donavanbecker** [comment]
Done

**Comment by dieugab** [comment]
@dnicolson Fantastic news! I'd love to try it. Should I try and edit the file on my local homebridge instance or are you currently working on a PR?

**Comment by dnicolson** [comment]
@gvssr I'm not working on a PR at the moment, you may as well modify the `curtain.js` file locally unless someone else makes a PR.

**Comment by dieugab** [comment]
@dnicolson I sudo edited my local file at `/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts` and removed cached accessoires, but it's still hanging on closing/opening for me. Did I edit the right file? Is there anything else I need to change?

![image](https://user-images.githubusercontent.com/61377476/152134206-b21d9e7e-4c79-4ebe-9278-3c6efdf9ea94.png)

![image](https://user-images.githubusercontent.com/61377476/152133907-8c1bfc65-05b2-4db1-bd2f-eda48e7580cd.png)

**Comment by donavanbecker** [comment]
> The problem appears to have been introduced in version 0.1.2-beta.1, it's related to the light sensor. Removing the following lines in the latest code appears to resolve the issue:
> 
> https://github.com/OpenWonderLabs/homebridge-switchbot/blob/dedabb43754f837c43d1d7ff3fbfc40e00d46877/src/device/curtain.ts#L121-L135

I have a hard time believing that this is the cause.

**Comment by donavanbecker** [comment]
@gvssr, I pushed a new beta, so you can try this.

**Comment by donavanbecker** [comment]
> @dnicolson I sudo edited my local file at `/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts` and removed cached accessoires, but it's still hanging on closing/opening for me. Did I edit the right file? Is there anything else I need to change?
> 
> ![image](https://user-images.githubusercontent.com/61377476/152134206-b21d9e7e-4c79-4ebe-9278-3c6efdf9ea94.png)

no.

**Comment by dieugab** [comment]
> @gvssr, I pushed a new beta, so you can try this.

Thank you! I updated to beta 1.12.2-beta 1, cleared accessoires cache en rebooted Homebridge but the issue sadly still persists
![image](https://user-images.githubusercontent.com/61377476/152136514-61559b84-6c52-4531-8bda-3940749e6e4a.png)

**Comment by donavanbecker** [comment]
closing till I see a PR, 

Sorry without being able to reproduce on my side, I have no way of fixing this.

**Comment by dnicolson** [comment]
What if you try the Home app @gvssr? With version `1.12.2-beta.1` I see "Opening..." and "Closing..." and not after reverting back to the `1.12.1`.

It appears as though there are other unrelated issues with Homebridge UI, many accessories failed to update but switching to "Config" and back to "Accessories" resulted in several accessories updating.

**Comment by dieugab** [comment]
@dnicolson I don't use it through the Home app, I use it in Home Asssistant and it's the same thing there:
![image](https://user-images.githubusercontent.com/61377476/152145541-d46c6b93-740e-4da2-ad59-d20d7fecb456.jpeg)

**Comment by dnicolson** [comment]
@gvssr I can confirm your issue is different and it seems that it was introduced with `1.0.3-beta.5`, https://github.com/OpenWonderLabs/homebridge-switchbot/pull/239 should fix it.

**Comment by donavanbecker** [comment]
Just merged #239 so new beta coming out. Wow! Can't believe I missed that easy bug...

**Comment by dieugab** [comment]
Latest version works… flawlessly! I just tested it here. @dnicolson thank you so much, you're my hero! And @donavanbecker thank you for being so patient with this issue.

**Comment by dnicolson** [comment]
@donavanbecker the Home app closing/unclosing issue persists. I think it could actually be related to the light component.

I see only `1` or `6001` lux units at all times. In the SwitchBot app, I see in the "Light Sensing (Beta)" menu a flatline constantly of `2`. Interestingly, if I change to the secondary unit I see a fluctuating graph.

The firmware on both units is `V2.8`.

**Comment by donavanbecker** [comment]
@dnicolson are you using OpenAPI or BLE?

BLE Sends me info 10 different amounts, if you set the maxLux and minLux then these numbers would divide by 9 and would set the value for each interval.

OpenAPI only sends me 2 either `dim` or `bright`. So it will always be either 1 or 6001 unless you change the maxLux and minLux.

@dnicolson, what do you have set for your config?

**Comment by donavanbecker** [comment]
> Latest version works… flawlessly! I just tested it here. @dnicolson thank you so much, you're my hero! And @donavanbecker thank you for being so patient with this issue.

good to hear, I will post a new update.

**Comment by dnicolson** [comment]
> @dnicolson are you using OpenAPI or BLE?

Mostly BLE, I only unboxed the Hub Mini a couple of days ago to debug the issue.

> @dnicolson, what do you have set for your config?

Just the defaults with a curtain (now I think the logging may be too verbose, feel free to revert 😅):

```
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "XXX",
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "logging": "standard"
                    }
                ],
                "irdevices": [
                    {
                        "logging": "standard"
                    }
                ],
                "logging": "standard"
            },
            "platform": "SwitchBot"
        }
``

**Comment by dnicolson** [comment]
> @dnicolson are you using OpenAPI or BLE?

Mostly BLE, I only unboxed the Hub Mini a couple of days ago to debug the issue.

> @dnicolson, what do you have set for your config?

Just the defaults with a curtain (now I think the logging may be too verbose, feel free to revert 😅):

```
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "XXX",
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "ble": true,
                        "logging": "standard"
                    }
                ],
                "irdevices": [
                    {
                        "logging": "standard"
                    }
                ],
                "logging": "standard"
            },
            "platform": "SwitchBot"
        }
```

And not to be pedantic, but a typo:
`The devices config section is missing the *Device ID* in the config, Check Your Conifg.`

**Comment by donavanbecker** [comment]
@dnicolson Thanks any spellcheck are appreciated!! 

Can you set min and max to like 10 and 90 and see if that resolves if for you?

**Comment by dnicolson** [comment]
Yeah, unfortunately still no opening/closing.

**Comment by donavanbecker** [comment]
> Yeah, unfortunately still no opening/closing.

Can you try the latest beta

**Comment by dnicolson** [comment]
I tried version `1.12.3-beta.5` and it hasn't resolved the issue. I'm fairly confident that the state and position are being set correctly from my testing, that doesn't appear to be the issue. Even though you don't see "Opening..." you see the loading spinner.

Maybe it's a bug in the Home app that doesn't show "Opening..." correctly with the addition of the light sensor, but @donavanbecker you do not see the issue?

1.12.2-beta.1:
![1 12 2-beta 1](https://user-images.githubusercontent.com/2276355/152584164-f4188249-9c2a-4c55-bb54-92a704740d8e.gif)

1.12.3-beta.5:
![1 12 3-beta 5](https://user-images.githubusercontent.com/2276355/152584175-ab493ea5-d4ae-4c92-9608-cbe28e4c4b23.gif)

**Comment by donavanbecker** [comment]
@dnicolson can you try the latest beta?

**Comment by dnicolson** [comment]
Unfortunately version `1.12.4-beta.1` hasn't resolved the issue.

**Comment by donavanbecker** [comment]
@dnicolson I think your right that this is a iOS bug
