### ISSUE TITLE
Bug: Bot failed pushChanges with BLE Connection

### ISSUE THREAD

**Issue by prophet42** [OpenWonderLabs/homebridge-switchbot#174]
### Describe Your Problem

Hi. When I try and use Homebridge-Switchbot plugin I get a "Bot failed pushChanges with BLE Connection" error. The Bot button appears in my accessories but it does not do anything. I do not have a hub. Thanks in advance!

### Relevant log output

```shell
[12/30/2021, 5:40:32 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "XXXXXXXXXXXX",
                "configDeviceName": "Bot",
                "configDeviceType": "Bot",
                "ble": true,
                "bot": {
                    "mode": "switch",
                    "deviceType": "switch"
                }
            }
        ]
    },
    "platform": "SwitchBot"
}
```

### Device & Model

Switchbot Bot

### Node.js Version

v16.13.1

### NPM Version

v8.1.2

### Homebridge Version

v1.3.9

### Homebridge SwitchBot Plugin Version

v1.5.0

### Homebridge Config UI X Plugin Version

v4.41.5

### Operating System

macOS

**Comment by donavanbecker** [comment]
Don't put the colons in your deviceID

**Comment by prophet42** [comment]
Thanks, but the same error without the colons.

[12/30/2021, 6:02:49 PM] [SwitchBot] Bot: Bot On: false
[12/30/2021, 6:03:03 PM] [SwitchBot] Bot: Bot On: true
[12/30/2021, 6:03:03 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection

**Comment by donavanbecker** [comment]
Can you post updated config?

Also what version of macOS? And have you followed the prerequisites for noble?

**Comment by prophet42** [comment]
Sure. It's macOS 10.15.7. The prerequisites for macOS appear to be to install Xcode (bluetooth isn't in security on Catalina). Is that correct?

{
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "XXXXXXXXXXXX",
                "configDeviceName": "Bot",
                "configDeviceType": "Bot",
                "ble": true,
                "bot": {
                    "mode": "switch",
                    "deviceType": "switch"
                }
            }
        ]
    },
    "platform": "SwitchBot"
}

**Comment by donavanbecker** [comment]
Can you update to the latest beta, then enable debug mode and send more logs

**Comment by prophet42** [comment]
Beta installed. Here are the debug logs. Thanks again!

[12/30/2021, 6:32:04 PM] [SwitchBot] [DEBUG] Bot: Bot On: false
[12/30/2021, 6:32:04 PM] [SwitchBot] [DEBUG] Bot: Bot BLE pushChanges
[12/30/2021, 6:32:04 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:32:04 PM] [SwitchBot] [DEBUG] Bot: Bot Press Mode: switch
[12/30/2021, 6:32:04 PM] [SwitchBot] Bot: Bot On: false
[12/30/2021, 6:32:06 PM] [SwitchBot] [DEBUG] Bot: Bot On: true
[12/30/2021, 6:32:07 PM] [SwitchBot] [DEBUG] Bot: Bot BLE pushChanges
[12/30/2021, 6:32:07 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:32:07 PM] [SwitchBot] [DEBUG] Bot: Bot Press Mode: switch
[12/30/2021, 6:32:09 PM] [SwitchBot] Bot: Bot On: true
[12/30/2021, 6:32:09 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection
[12/30/2021, 6:32:09 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection, Error Message: "Now connecting. Wait for a few seconds then try again."
[12/30/2021, 6:32:09 PM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/30/2021, 6:32:09 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:32:12 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:32:12 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:32:12 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:32:12 PM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/30/2021, 6:32:12 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:32:15 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:32:15 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:32:15 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:32:15 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:32:15 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:32:15 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: true
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 87
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: true
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 87
[12/30/2021, 6:32:19 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0
[12/30/2021, 6:32:22 PM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/30/2021, 6:32:22 PM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: true
[12/30/2021, 6:32:22 PM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 87
[12/30/2021, 6:32:22 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: true
[12/30/2021, 6:32:22 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 87
[12/30/2021, 6:32:22 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0
[12/30/2021, 6:33:20 PM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/30/2021, 6:33:20 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:33:21 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:33:21 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:33:21 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:33:24 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:33:24 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:33:24 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:33:30 PM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/30/2021, 6:33:30 PM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: true
[12/30/2021, 6:33:30 PM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 87
[12/30/2021, 6:33:30 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: true
[12/30/2021, 6:33:30 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 87
[12/30/2021, 6:33:30 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0

**Comment by donavanbecker** [comment]
Looking at these logs it looks like it connected.

**Comment by prophet42** [comment]
Yes, I was thinking that too. But I still can't control it. Logs from when I push the button:

[12/30/2021, 6:49:42 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection
[12/30/2021, 6:49:42 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection, Error Message: "Now connecting. Wait for a few seconds then try again."
[12/30/2021, 6:49:47 PM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/30/2021, 6:49:47 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:49:49 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:49:49 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:49:49 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:49:52 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:49:52 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:49:52 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:49:55 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":87}
[12/30/2021, 6:49:55 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 87
[12/30/2021, 6:49:55 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:49:57 PM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/30/2021, 6:49:57 PM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: true
[12/30/2021, 6:49:57 PM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 87
[12/30/2021, 6:49:57 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: true
[12/30/2021, 6:49:57 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 87
[12/30/2021, 6:49:57 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0

**Comment by prophet42** [comment]
I notice the state it loads the switch in is incorrect. The accessory shows as "on" but the bot is in the off position. Also, when I hit the button in Homebridge the button switches to off, but after a few moments it turns itself back on. Here are the logs around when that happens:

[12/30/2021, 6:54:54 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: true
[12/30/2021, 6:54:54 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 85
[12/30/2021, 6:54:54 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0
[12/30/2021, 6:55:56 PM] [SwitchBot] [DEBUG] Bot: Bot On: false
[12/30/2021, 6:56:02 PM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/30/2021, 6:56:02 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/30/2021, 6:56:02 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":85}
[12/30/2021, 6:56:02 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 85
[12/30/2021, 6:56:02 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:56:03 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":85}
[12/30/2021, 6:56:03 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 85
[12/30/2021, 6:56:03 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:56:06 PM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":85}
[12/30/2021, 6:56:06 PM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 85
[12/30/2021, 6:56:06 PM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/30/2021, 6:56:12 PM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/30/2021, 6:56:12 PM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: true
[12/30/2021, 6:56:12 PM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 85
[12/30/2021, 6:56:12 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: true
[12/30/2021, 6:56:12 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 85
[12/30/2021, 6:56:12 PM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0

**Comment by donavanbecker** [comment]
@prophet42, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.5.1-beta.5/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by prophet42** [comment]
Hi. I already updated to the beta. You asked me to previously. Cheers.

Matt

**Comment by donavanbecker** [comment]
@prophet42 Yes, but I pushed a new beta out.

**Comment by prophet42** [comment]
Oh, sorry. I misread your message and thought it said "beta.3" not "5". I've updated now. The bot now loads as "off" in accessories but I still can't control it. Thanks for all your help!

[12/31/2021, 8:32:31 AM] [SwitchBot] [DEBUG] Bot: Bot On: true
[12/31/2021, 8:32:31 AM] [SwitchBot] [DEBUG] Bot: Bot BLE pushChanges
[12/31/2021, 8:32:31 AM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/31/2021, 8:32:31 AM] [SwitchBot] [DEBUG] Bot: Bot Press Mode: switch
[12/31/2021, 8:32:33 AM] [SwitchBot] Bot: Bot On: true
[12/31/2021, 8:32:35 AM] [SwitchBot] [DEBUG] Bot: Bot On: false
[12/31/2021, 8:32:35 AM] [SwitchBot] [DEBUG] Bot: Bot BLE pushChanges
[12/31/2021, 8:32:35 AM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/31/2021, 8:32:35 AM] [SwitchBot] [DEBUG] Bot: Bot Press Mode: switch
[12/31/2021, 8:32:36 AM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/31/2021, 8:32:36 AM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot serviceData: {"model":"H","modelName":"WoHand","mode":true,"state":true,"battery":85}
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot, model: H, modelName: WoHand, mode: true, state: true, battery: 85
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot connected: true
[12/31/2021, 8:32:37 AM] [SwitchBot] Bot: Bot On: false
[12/31/2021, 8:32:37 AM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection
[12/31/2021, 8:32:37 AM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection, Error Message: "Now connecting. Wait for a few seconds then try again."
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: false
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 85
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: false
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 85
[12/31/2021, 8:32:37 AM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0
[12/31/2021, 8:32:40 AM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus
[12/31/2021, 8:32:40 AM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: XX:XX:XX:XX:XX:XX
[12/31/2021, 8:32:41 AM] [SwitchBot] [DEBUG] Bot: Bot BLE parseStatus
[12/31/2021, 8:32:41 AM] [SwitchBot] [DEBUG] Bot: Bot Switch Mode, mode: true, On: false
[12/31/2021, 8:32:41 AM] [SwitchBot] [DEBUG] Bot: Bot BatteryLevel: 85
[12/31/2021, 8:32:41 AM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic On: false
[12/31/2021, 8:32:41 AM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic BatteryLevel: 85
[12/31/2021, 8:32:41 AM] [SwitchBot] [DEBUG] Bot: Bot updateCharacteristic StatusLowBattery: 0

**Comment by donavanbecker** [comment]
Try controlling more then once. Push fails when doing refresh at the same time.

**Comment by prophet42** [comment]
I am not sure what you mean by try controlling more than once. Press the virtual button in Homebridge more than once? I've pressed it repeatedly. Here are the logs:

12/31/2021, 11:21:18 AM] [SwitchBot] Bot: Bot On: false
[12/31/2021, 11:21:18 AM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection
[12/31/2021, 11:21:18 AM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection, Error Message: "Cannot read properties of undefined (reading 'turnOff')"

**Comment by donavanbecker** [comment]
@prophet42 can you try v1.7.0

**Comment by prophet42** [comment]
Just did. No luck.

Matt

**Comment by donavanbecker** [comment]
> Just did. No luck.
> 
> Matt
> On Jan 6, 2022, 12:48 AM -0500, Donavan Becker ***@***.***>, wrote:
> > @prophet42 can you try v1.7.0
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> > You are receiving this because you were mentioned.Message ID: ***@***.***>
> 

Can you elaborate?

**Comment by prophet42** [comment]
Hey. Sorry I am out of town, so I am doing it remotely. I installed the update and still could not control the bot. But, actually just now I was able to turn it on once (my wife checked for me), but I can't turn it off. I'll paste the logs below. I did wait and try again but no luck controlling it then either. Thanks again for your help.

[1/6/2022, 6:00:28 PM] [SwitchBot] [DEBUG] Bot: Bot BLE Address: 
[1/6/2022, 6:00:28 PM] [SwitchBot] [DEBUG] Bot: Bot Press Mode: switch
[1/6/2022, 6:00:32 PM] [SwitchBot] Bot: Bot On: false
[1/6/2022, 6:00:32 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection
[1/6/2022, 6:00:32 PM] [SwitchBot] Bot: Bot failed pushChanges with BLE Connection, Error Message: "Now connecting. Wait for a few seconds then try again."
[1/6/2022, 6:00:33 PM] [SwitchBot] [DEBUG] Bot: Bot BLE refreshStatus

**Comment by donavanbecker** [comment]
@prophet42, is there anyway you can put this right by your homebridge device and see if its working?

**Comment by prophet42** [comment]
Hi. Unfortunately, I am not in town and it is an iMac so it’s too big a job to ask my wife to do. I won’t be back for months. I do have another SwitchBot where I am and I installed the plugin in my Homebridge here to see if it would work here. It doesn’t work either. Here I am using a MacBook Pro (2020) with macOS 12.1. I did the extra prerequisite of allowing Terminal to access bluetooth. I’ve pasted the logs from here if you are curious. I did try going right beside the bot here.

Matt

[1/7/2022, 6:30:33 PM] [SwitchBot] Initializing SwitchBot platform...
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Finished initializing platform:
[1/7/2022, 6:30:33 PM] [SwitchBot] Missing openToken
[1/7/2022, 6:30:33 PM] [SwitchBot] Cloud Enabled SwitchBot Devices & IR Devices will not work
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Config OK
[1/7/2022, 6:30:33 PM] [SwitchBot] Loading accessory from cache: Bot 60
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Executed didFinishLaunching callback
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] SwitchBot Device Manual Config Set: [{"deviceId":"XXXXXXXXXXX","configDeviceName":"Bot 60","configDeviceType":"Bot","ble":true,"scanDuration":10,"bot":{"mode":"switch","deviceType":"switch"}}]
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Discovered Bot: XXXXXXXXXXX
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Device: Bot 60 BLE Connection Enabled
[1/7/2022, 6:30:33 PM] [SwitchBot] Restoring existing accessory from cache: Bot 60 DeviceID: XXXXXXXXXXX
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] "switch"
[1/7/2022, 6:30:33 PM] [SwitchBot] Bot: Bot 60 Using Platform Config Logging: debug
[1/7/2022, 6:30:33 PM] [SwitchBot] Bot: Bot 60 Using Device Config scanDuration: 10
[1/7/2022, 6:30:33 PM] [SwitchBot] Bot: Bot 60 Using Platform Config refreshRate: 120
[1/7/2022, 6:30:33 PM] [SwitchBot] Bot: Bot 60 Using Bot Mode: switch
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 Config: (ble: true, offline: undefined, mode: switch, deviceType: switch, doublePress: 1)
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 BLE refreshStatus
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 BLE Address: XX:XX:XX:XX:XX:XX
[1/7/2022, 6:30:33 PM] [SwitchBot] Bot: Bot 60 Displaying as Switch
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 updateCharacteristic On: false
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 updateCharacteristic BatteryLevel: 100
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 updateCharacteristic StatusLowBattery: 0
[1/7/2022, 6:30:33 PM] [SwitchBot] [DEBUG] Bot uuid: XXXXXXXXXXX-Bot, (9bf4ec07-d8f7-45b5-b677-addb23c5b29a)
[1/7/2022, 6:30:43 PM] [SwitchBot] Bot: Bot 60 wasn't able to establish BLE Connection
[1/7/2022, 6:32:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 BLE refreshStatus
[1/7/2022, 6:32:33 PM] [SwitchBot] [DEBUG] Bot: Bot 60 BLE Address: XX:XX:XX:XX:XX:XX
[1/7/2022, 6:32:43 PM] [SwitchBot] Bot: Bot 60 wasn't able to establish BLE Connection

**Comment by donavanbecker** [comment]
I also added `npm` and `node` to my Bluetooth. This is working for me.

You can find where they are installed by doing terminal: `which node` and `which npm`

**Comment by prophet42** [comment]
Hi Donovan. I am note sure what you mean by this. They are located at:
/usr/local/bin/node
/usr/local/bin/npm

Matt

**Comment by donavanbecker** [comment]
navigate to those folders and drag them into the bluetooth security section like you did Terminal.

**Comment by prophet42** [comment]
Oh, I see. Thanks! I dragged them there successfully, but the Bot still can’t connect.

[1/16/2022, 9:04:21 PM] [SwitchBot] Bot: Bot 60 wasn't able to establish BLE Connection

Matt

**Comment by donavanbecker** [comment]
@prophet42 You have Xcode installed?

**Comment by prophet42** [comment]
I do have Xcode.

Matt

**Comment by donavanbecker** [comment]
> I do have Xcode.
> 
> Matt
> On Jan 16, 2022, 9:55 PM -0500, Donavan Becker ***@***.***>, wrote:
> > @prophet42 You have Xcode installed?
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> > You are receiving this because you were mentioned.Message ID: ***@***.***>
> 

And I am guessing you have accepted the terms & Conditions?

**Comment by prophet42** [comment]
Of Xcode? Yes. I use Xcode for other things as well.

Matt

**Comment by donavanbecker** [comment]
@prophet42 I would say then till this [issue](https://github.com/abandonware/noble/issues/225) is resolved, BLE won't work.

**Comment by rolandjaeger** [comment]
Hi Donavan!

I encountered the same problem when trying to configure a switch bot to work with Bluetooth only.
First, it worked without any problems. But after playing around a bit with the config (my Raspi Zero 2 W apparently needs a bit longer scan time than just one second), it suddenly stopped working and I got the following in the log during init: 
`Failed to Discover Devices: Unauthorized Request`
and after that, when trying to trigger it
`Bot failed pushChanges with BLE Connection`

After digging a bit deeper, I noticed that the config suddenly containted these two lines:
`            "credentials": {
                "openToken": "admin",
                "notice": "Keep your token a secret!"
            },`
When I remove them, everything is working fine again.

But every time I make changes to the config through the GUI, these lines are added again (probably because the OpenAPI Token field is a mandatory field) and the apparently the connection attempt is made via OpenAPI despite having set the connection method to BLE.

Hope that helps! Let me know if you need more details.

Thank you for the great work!

**Comment by prophet42** [comment]
Thanks for the suggestion @rolandjaeger! I gave it a try, but to no avail. It may be the macOS issue that @donavanbecker mentioned mentioned in the previous comment. Thanks for both your help!
