### ISSUE TITLE
Feature Request: Add Support for SwitchBot Lock

### ISSUE THREAD

**Issue by kokono9201** [OpenWonderLabs/homebridge-switchbot#226]
### Problem

Swithbot lock

### Solution

the switchbot lock is now on sale. Could it be possible adding the support to the lock?

**Comment by donavanbecker** [comment]
@a408498672 Yes, I will look at adding it soon.

But I am not seeing it on the SwitchBot website yet.

**Comment by kokono9201** [comment]
It already updated on Japan homepage and amazon so I have one. Maybe other region is delayed. If u need any information of the hardware in advance, I may help.

**Comment by donavanbecker** [comment]
@a408498672 can you install the latest beta? and get me the logs that log in yellow? it should be the `lockstate` and `doorstate` then I will be able to know how to handle this.

Not enough info in the [OpenAPI Document](https://github.com/OpenWonderLabs/SwitchBotAPI) to just impliment.

**Comment by kokono9201** [comment]
@donavanbecker 
i'm not sure i was doing right. i updated to v1.10.2-beta.4 but i didn't find the information from the homebridge log. 

```
{"deviceId":"XXXXXXXXXXX","deviceName":"gate","deviceType":"Smart Lock","enableCloudService":true,"hubDeviceId":"XXXXXXXXXXX"}
Device: gate with Device Type: Smart Lock, is currently not supported.
gate deviceInfoStatus: {"statusCode":100,"body":{},"message":"success"}
```

**Comment by donavanbecker** [comment]
@a408498672, okay that helps. I have just pushed another beta. Please update and repost all logs for Lock

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.10.2-beta.5/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by kokono9201** [comment]
@donavanbecker 

```
[DEBUG] Discovered Smart Lock: XXXXXXXXXXX
Restoring existing accessory from cache: gate DeviceID: XXXXXXXXXXX
[DEBUG] Smart Lock uuid: XXXXXXXXXXX-Smart Lock, (XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
```

**Comment by donavanbecker** [comment]
@a408498672 

there should be more logs then that. I just posted a new beta that should have a log that contains 

`COPY THIS LOG`

I need that log.

**Comment by kokono9201** [comment]
@donavanbecker 
sorry, i've already updated to beta7 but i still can't find that log.
https://imgur.com/PX6dP4U
did i search in the wrong place?

**Comment by donavanbecker** [comment]
can you hide that device using the SwitchBot Device Settings or clear cache using Homebridge Settings? Then restart this will remove the device. 

if you do the config, then unhide the device and restart again. see if that triggers anything.

**Comment by kokono9201** [comment]
Lock: gate lockState: undefined (COPY THIS LOG)
should be this one?

**Comment by donavanbecker** [comment]
@a408498672 As I suspected. The API, is not displaying the lock yet. We will have to wait till that doesn't say undefined. Or once they merge the [lock PR](https://github.com/OpenWonderLabs/SwitchBotAPI/pull/85) then it will probably be supported.

**Comment by donavanbecker** [comment]
> can you hide that device using the SwitchBot Device Settings or clear cache using Homebridge Settings? Then restart this will remove the device.
> 
> if you do the config, then unhide the device and restart again. see if that triggers anything.

Can you do this again? after update to the latest Beta? It won't make the Lock work, but needs to be done because I am guessing currently your lock is showing as a Outlet and will now display as a Lock.

**Comment by kokono9201** [comment]
yes. it displays as a lock now.

**Comment by grandevice** [comment]
displays as a lock
but unidentified

**Comment by donavanbecker** [comment]
> displays as a lock
> 
> but unidentified

As stated before we have to wait for the API

**Comment by Minsheng** [comment]
> 

I tested it out yesterday and got the lockState: undefined error, too. In Home app, it kept showing "locking...".
The problem has been fixed just now. Please test it out.

**Comment by donavanbecker** [comment]
@Minsheng Did you fix this on the API side?

**Comment by donavanbecker** [comment]
> displays as a lock
> but unidentified

@grandevice, should be corrected now.

**Comment by jausto** [comment]
@donavanbecker This is not working for me.

If added it to the device section but still getting errors like this.
[SwitchBot] Adding new accessory: Door Bot DeviceID: DD2F23F7A318
[4/5/2022, 5:51:23 PM] [SwitchBot] Bot: Door does not have bot mode set in the Plugin's SwitchBot Device Settings,
[4/5/2022, 5:51:23 PM] [SwitchBot] Bot: Door is defaulting to "switch" mode, you may experience issues.
[4/5/2022, 5:51:23 PM] [SwitchBot] Bot: Door Config: {"refreshRate":30}
[4/5/2022, 5:51:23 PM] [SwitchBot] Bot: Door Displaying as Outlet
[4/5/2022, 5:55:35 PM] [Homebridge UI] [@switchbot/homebridge-switchbo

**Comment by 1uci3n** [comment]
It keeps showing unlocking for me, I can't operate it from homekit and homebridge.

**Comment by donavanbecker** [comment]
@1uci3n you won't be able to operate it. API only supports view the state.

**Comment by 1uci3n** [comment]
> @1uci3n you won't be able to operate it. API only supports view the state.

Is there any other way for me to control my door lock from homekit ？

**Comment by donavanbecker** [comment]
> > @1uci3n you won't be able to operate it. API only supports view the state.
> 
> Is there any other way for me to control my door lock from homekit ？

no unless you can push a Pull Request with Bluetooth support?

**Comment by 1uci3n** [comment]
> > > @1uci3n you won't be able to operate it. API only supports view the state.
> > 
> > 
> > Is there any other way for me to control my door lock from homekit ？
> 
> no unless you can push a Pull Request with Bluetooth support?

Thank you for your patient answer

**Comment by Jacksonbm1** [comment]
Ok, so I see a bunch of features being pulled in, are these ble or based on the hub integration? It's hard for me to tell  – I suspect because this is all beta. Just trying to understand the state of the plugin

**Comment by donavanbecker** [comment]
OpenAPI

**Comment by Jacksonbm1** [comment]
Is the open api hub only?

**Comment by donavanbecker** [comment]
@Jacksonbm1 Yes
