### ISSUE TITLE
Support Request:  Bot does not react.

### ISSUE THREAD

**Issue by domeOo** [OpenWonderLabs/homebridge-switchbot#242]
### Describe Your Problem

Bot does not react when i activate over Homekit. I'm using a rpi4 with docker. 

### Relevant log output

```shell
homebridge-deCONZ_1  | [2/3/2022, 4:30:10 PM] [SwitchBot] Restarting child bridge...
homebridge-deCONZ_1  | [2/3/2022, 4:30:15 PM] [SwitchBot] Child bridge process ended
homebridge-deCONZ_1  | [2/3/2022, 4:30:15 PM] [SwitchBot] Process Ended. Code: 143, Signal: null
homebridge-deCONZ_1  | [2/3/2022, 4:30:22 PM] [SwitchBot] Restarting Process...
homebridge-deCONZ_1  | [2/3/2022, 4:30:23 PM] [SwitchBot] Launched child bridge with PID 19337
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Loaded @switchbot/homebridge-switchbot v1.12.2 child bridge successfully
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Using Config Logging: debug
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Finished initializing platform:
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Platform Config: {"logging":"debug"}
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] The devices config section is missing the *Device ID* in the config, Check Your Conifg.
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] The devices config section is missing the *Device Type* in the config, Check Your Conifg.
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Using Default Push Rate.
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Missing openToken
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Cloud Enabled SwitchBot Devices & IR Devices will not work
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Using Default Refresh Rate (2 minutes).
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Config OK
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Loading accessory from cache: Kaffemaschine
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Executed didFinishLaunching callback
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] SwitchBot Device Manual Config Set: [{"deviceId":"d06cee53186f","configDeviceName":"Kaffemaschine","configDeviceType":"Bot","ble":true,"scanDuration":2,"bot":{"mode":"press","deviceType":"outlet","allowPush":true,"doublePress":2,"maxRetry":5},"refreshRate":360,"logging":"debug"}]
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Discovered Bot: xxxxxxxxxxxxxx
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Device: Kaffemaschine BLE Connection Enabled
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Restoring existing accessory from cache: Kaffemaschine DeviceID: d06cee53186f
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] "press"
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Using Device Config Logging: debug
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Using Device Config scanDuration: 2
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Using Device Config refreshRate: 360
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Using Bot Mode: press
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Allowing Push Changes: true
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] Bot: Kaffemaschine Config: {"mode":"press","deviceType":"outlet","allowPush":true,"doublePress":2,"maxRetry":5,"ble":true,"logging":"debug","refreshRate":360,"scanDuration":2}
homebridge-deCONZ_1  | [2/3/2022, 4:30:24 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE refreshStatus
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] Bot: Kaffemaschine Displaying as Outlet
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Add Battery Service
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine updateCharacteristic On: false
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine updateCharacteristic BatteryLevel: 100
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine updateCharacteristic StatusLowBattery: 0
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] [DEBUG] Bot uuid: XXXXXXX-Bot, (XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX)
homebridge-deCONZ_1  | [2/3/2022, 4:30:25 PM] [SwitchBot] [DEBUG] Curtain: Kaffemaschine BLE Address: XX:XX:XX:XX:XX:XX



homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine On: true
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE pushChanges On: true OnCached: undefined
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE pushChanges
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Curtain: Kaffemaschine BLE Address: xx:xx:xx:xx:xx:xx
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Bot Mode: press
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE pushChanges On: true OnCached: true
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE pushChanges
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Curtain: Kaffemaschine BLE Address: xx:xx:xx:xx:xx:xx
homebridge-deCONZ_1  | [2/3/2022, 4:33:56 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine Bot Mode: press
homebridge-deCONZ_1  | [2/3/2022, 4:34:01 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE refreshStatus
homebridge-deCONZ_1  | [2/3/2022, 4:34:01 PM] [SwitchBot] [DEBUG] Curtain: Kaffemaschine BLE Address: xx:xx:xx:xx:xx:xx
homebridge-deCONZ_1  | [2/3/2022, 4:34:01 PM] [SwitchBot] [DEBUG] Bot: Kaffemaschine BLE refreshStatus
homebridge-deCONZ_1  | [2/3/2022, 4:34:01 PM] [SwitchBot] [DEBUG] Curtain: Kaffemaschine BLE Address: xx:xx:xx:xx:xx:xx
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "xxxxxxxxxx",
                        "configDeviceName": "Kaffeemaschine",
                        "configDeviceType": "Bot",
                        "ble": true,
                        "scanDuration": 2,
                        "bot": {
                            "mode": "press",
                            "deviceType": "outlet",
                            "allowPush": true,
                            "doublePress": 2,
                            "maxRetry": 5
                        },
                        "refreshRate": 360,
                        "logging": "debug"
                    }
                ],
                "irdevices": [
                    {
                        "logging": "standard"
                    }
                ],
                "logging": "debug"
            },
            "platform": "SwitchBot"
        }
```

### Device & Model

SwitchBot Bot

### Node.js Version

v16.13.2

### NPM Version

v8.1.2

### Homebridge Version

v1.4

### Homebridge SwitchBot Plugin Version

v1.12.2

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Docker

**Comment by domeOo** [comment]
I also find it strange that there is always something about curtains in the logs. 
I hope you can help me, thank you!

**Comment by donavanbecker** [comment]
> I also find it strange that there is always something about curtains in the logs.
> I hope you can help me, thank you!

this is a copy code accident. resolved in the latest beta

**Comment by donavanbecker** [comment]
@domeOo, looking through the logs it looks like the plugin isn't connecting through BLE to the Bot.

**Comment by domeOo** [comment]
Thx for the quick reply. I updated to the latest beta and the problem with the logs is gone. But The bot is still not doing anything. I use docker and I let the container run in privileged mode. Am i missing something?

**Comment by donavanbecker** [comment]
did you look at the [prerequisites](https://github.com/homebridge/noble#prerequisites) for Docker?

**Comment by molgar** [comment]
I am having this same issue with two Bots, stable and beta versions, installed on RPi non-docker.

**Comment by donavanbecker** [comment]
> I am having this same issue with two Bots, stable and beta versions, installed on RPi non-docker.

@molgar did you look at the [prerequisites](https://github.com/homebridge/noble#prerequisites)?

**Comment by domeOo** [comment]
> did you look at the [prerequisites](https://github.com/homebridge/noble#prerequisites) for Docker?

Sorry had overlooked that there is an extra section for docker. Now everything works. I can post tonight again what I had to do exactly if it is desired?

Thanks for your help you can close the ticket.

**Comment by donavanbecker** [comment]
> I can post tonight again what I had to do exactly if it is desired?

That would help for anyone that stumbles upon this issue.
