### ISSUE TITLE
Bug: error message: getaddrinfo EAI_AGAIN api.switch-bot.com

### ISSUE THREAD

**Issue by badxhabit** [OpenWonderLabs/homebridge-switchbot#671]
### Describe The Bug

API is failing to connect.

### To Reproduce

Always

### Expected behavior

Return status of devices

### Relevant log output

```shell
[03/02/2023, 21:21:33] [SwitchBot] Meter: Thermometer & Hygrometer error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:21:37] [SwitchBot] Curtain: Master Bedroom Curtains error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:21:43] [SwitchBot] Curtain: Curtain error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:23:30] [SwitchBot] Meter: Thermometer & Hygrometer error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:23:30] [SwitchBot] Curtain: Master Bedroom Curtains error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:27:30] [SwitchBot] Meter: Thermometer & Hygrometer error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:27:30] [SwitchBot] Curtain: Master Bedroom Curtains error message: getaddrinfo EAI_AGAIN api.switch-bot.com
[03/02/2023, 21:27:40] [SwitchBot] Curtain: Curtain error message: getaddrinfo EAI_AGAIN api.switch-bot.com
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "HomebridgePI",
        "username": “xxxxx”,
        "port": xxxx,
        "pin": “xxxxxx”,
        "advertiser": "bonjour-hap",
        "bind": [
            "eth0"
        ]
    },
    "description": "This is a configuration file with all supported devices.",
    "platforms": [
        {
            "name": "SwitchBot",
            "credentials": {
                "token": “xxxxx”,
                "secret": “xxxx”,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": “xxxx”,
                        "configDeviceName": "Thermometer & Hygrometer",
                        "configDeviceType": "Meter",
                        "connectionType": "OpenAPI",
                        "bot": {
                            "deviceType": "outlet"
                        },
                        "meter": {
                            "hide_humidity": false
                        },
                        "history": false,
                        "logging": "standard"
                    },
                    {
                        "deviceId": “xxxx”,
                        "configDeviceName": "Curtain",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "logging": "standard"
                    },
                    {
                        "deviceId": “xxxxxx”,
                        "configDeviceName": "Master Bedroom Curtains",
                        "configDeviceType": "Curtain",
                        "connectionType": "OpenAPI",
                        "logging": "standard"
                    }
                ],
                "logging": "standard"
            },
            "platform": "SwitchBot"
        }
    ]
}
```

### Device & Model

RPI 4, 4GB

### Node.js Version

v18.13.0

### NPM Version

v8.19.3

### Homebridge Version

v1.6.0

### Homebridge Switchbot Plugin Version

v2.5.1

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
this would be a networking issue

**Comment by badxhabit** [comment]
Networking issue with Switchbot?

All my other non-switchbot devices are connecting without issue.

**Comment by aferrar** [comment]
Can confirm same issue

**Comment by aferrar** [comment]
Fixed by restarting docker container. It was, indeed, a network issue on my end.

**Comment by badxhabit** [comment]
I restarted my RPI and can confirm that I am still having this issue. 

Not sure if this is related yet, but at Midnight I started receiving responses from the server again, then it stopped at ~12:39PM today.
