### ISSUE TITLE
Bug: Battery reporting wrong (Curtain2)

### ISSUE THREAD

**Issue by thechris1992** [OpenWonderLabs/homebridge-switchbot#805]
### Describe the Bug

Hey Guys,

HomeKit Battery level: 0%
Homebridge: 0% 
SwitchBot app: 77%

and the API… (log)

### To Reproduce

Connect Curtain 2 and check the battery level? 

### Expected Behavior

HomeKit @ the same Battery level as the SwitchBot App. 

### Relevant Log Output

```shell
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ body: {"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":{"data":{"type":"Buffer","data":[123,34,115,116,97,116,117,115,67,111,100,101,34,58,49,48,48,44,34,98,111,100,121,34,58,123,34,100,101,118,105,99,101,73,100,34,58,34,68,51,49,48,66,66,53,52,48,57,70,51,34,44,34,100,101,118,105,99,101,84,121,112,101,34,58,34,67,117,114,116,97,105,110,34,44,34,104,117,98,68,101,118,105,99,101,73,100,34,58,34,69,56,53,54,54,50,65,49,51,57,65,57,34,44,34,99,97,108,105,98,114,97,116,101,34,58,116,114,117,101,44,34,103,114,111,117,112,34,58,102,97,108,115,101,44,34,109,111,118,105,110,103,34,58,50,44,34,115,108,105,100,101,80,111,115,105,116,105,111,110,34,58,50,44,34,118,101,114,115,105,111,110,34,58,34,86,54,46,51,34,44,34,98,97,116,116,101,114,121,34,58,57,57,125,44,34,109,101,115,115,97,103,101,34,58,34,115,117,99,99,101,115,115,34,125]},"next":null},"tail":{"data":{"type":"Buffer","data":[123,34,115,116,97,116,117,115,67,111,100,101,34,58,49,48,48,44,34,98,111,100,121,34,58,123,34,100,101,118,105,99,101,73,100,34,58,34,68,51,49,48,66,66,53,52,48,57,70,51,34,44,34,100,101,118,105,99,101,84,121,112,101,34,58,34,67,117,114,116,97,105,110,34,44,34,104,117,98,68,101,118,105,99,101,73,100,34,58,34,69,56,53,54,54,50,65,49,51,57,65,57,34,44,34,99,97,108,105,98,114,97,116,101,34,58,116,114,117,101,44,34,103,114,111,117,112,34,58,102,97,108,115,101,44,34,109,111,118,105,110,103,34,58,50,44,34,115,108,105,100,101,80,111,115,105,116,105,111,110,34,58,50,44,34,118,101,114,115,105,111,110,34,58,34,86,54,46,51,34,44,34,98,97,116,116,101,114,121,34,58,57,57,125,44,34,109,101,115,115,97,103,101,34,58,34,115,117,99,99,101,115,115,34,125]},"next":null},"length":1},"length":215,"pipes":[],"flowing":null,"ended":true,"endEmitted":false,"reading":false,"constructed":true,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":0}
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ statusCode: 200
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ headers: {"date":"Sun, 27 Aug 2023 20:46:08 GMT","content-type":"application/json","content-length":"215","connection":"keep-alive","x-amzn-requestid":"7ea41c59-56fc-45a6-8033-c8efcf009cb6","x-amz-apigw-id":"KVlimF8oIAMEX4w=","x-amzn-trace-id":"Root=1-64ebb610-514305d47df3393b2956067a;Sampled=0;lineage=bf95bacf:0"}
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ deviceStatus: {"statusCode":100,"body":{"deviceId":"D310BB5409F3","deviceType":"Curtain","hubDeviceId":"E85662A139A9","calibrate":true,"group":false,"moving":2,"slidePosition":2,"version":"V6.3","battery":99},"message":"success"}
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ deviceStatus body: {"deviceId":"D310BB5409F3","deviceType":"Curtain","hubDeviceId":"E85662A139A9","calibrate":true,"group":false,"moving":2,"slidePosition":2,"version":"V6.3","battery":99}
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ deviceStatus statusCode: 100
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ statusCode: 200 & deviceStatus StatusCode: 100
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ openAPIparseStatus
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain Vorhang WZ CurrentPosition: 98
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ Standby, CurrentPosition: 98
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ Stopped
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ CurrentPosition: 98, TargetPosition: 98, PositionState: 2,
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ CurrentAmbientLightLevel: 6001
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ updateCharacteristic CurrentPosition: 98
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ updateCharacteristic PositionState: 2
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ updateCharacteristic TargetPosition: 98
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ updateCharacteristic CurrentAmbientLightLevel: 6001
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ BatteryLevel: undefined
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ StatusLowBattery: undefined
[27/08/2023, 22:46:08] [SwitchBot] [DEBUG] Curtain: Vorhang WZ updateCharacteristic FirmwareRevision: V6.3
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "token": "",
                "secret": "",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 360,
                "pushRate": 1,
                "logging": "standard"
            },
            "_bridge": {
                "username": "",
                "port":
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/17517167/831b0772-c843-4405-8d5c-900e0d160a64)

![image](https://github.com/OpenWonderLabs/homebridge-switchbot/assets/17517167/12ba886d-508f-404b-857e-ec6d05d1a663)

### Device and Model

raspberry Pi 3

### Node.js Version

18.17.1

### NPM Version

-

### Homebridge Version

1.6.1

### Homebridge Switchbot Plugin Version

2.8.1

### Homebridge Config UI X Plugin Version

4.50.5

### Operating System

raspi light

**Comment by donavanbecker** [comment]
Version 2.8.2 has been released and should resolve this.

**Comment by thechris1992** [comment]
Now the Homebridge & HomeKit match’s the API, thanks @donavanbecker!

But still wrong between the API vs SwitchBot app. 

SwitchBot Hub (1) FW: V5.4-3.8
@SwitchBot @SwitchBot-Wonderlabs
